/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_quadroid_ndk_QuadroidLib */

#ifndef _Included_io_quadroid_UDPSensor_ndk_QuadroidLib
#define _Included_io_quadroid_UDPSensor_ndk_QuadroidLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_quadroid_ndk_QuadroidLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_quadroid_UDPSensor_ndk_QuadroidLib_init
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL JNI_OnLoad
	(JavaVM *, void *);

#ifdef __cplusplus
}
#endif
#endif
